"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path

# ========================
# 🔧 RUTAS Y CONFIG BÁSICA
# ========================

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-z)ef_&ohvg#38ntgcy3#fcf@#p)72_sk7$eah&ukuba$x%!gyl'
DEBUG = True
ALLOWED_HOSTS = []


# ========================
# 🗄️ CONFIGURACIÓN BASE DE DATOS (MySQL con XAMPP)
# ========================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'misionemprende',  # 👈 Debe existir en phpMyAdmin
        'USER': 'root',            # Usuario por defecto en XAMPP
        'PASSWORD': '',            # 👈 SIN contraseña (deja vacío)
        'HOST': 'localhost',       # Servidor local
        'PORT': '3306',            # Puerto MySQL por defecto
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# ========================
# ⚙️ APLICACIONES INSTALADAS
# ========================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'juego',  # Tu app principal
]


# ========================
# 🧱 MIDDLEWARE
# ========================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ========================
# 🌐 CONFIGURACIÓN DE URLs Y PLANTILLAS
# ========================

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 👈 carpeta templates global
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ========================
# 🔒 VALIDADORES DE CONTRASEÑAS
# ========================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ========================
# 🌍 LOCALIZACIÓN
# ========================

LANGUAGE_CODE = 'es-cl'  # Español Chile
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True


# ========================
# 🖼️ ARCHIVOS ESTÁTICOS
# ========================

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# ========================
# 🔑 PRIMARY KEY POR DEFECTO
# ========================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

