# Generated by Django 5.0.6 on 2025-10-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idalumno', models.AutoField(db_column='idAlumno', primary_key=True, serialize=False)),
                ('emailalumno', models.CharField(blank=True, db_column='emailAlumno', max_length=100, null=True)),
                ('nombrealumno', models.CharField(blank=True, db_column='nombreAlumno', max_length=200, null=True)),
                ('carreraalumno', models.CharField(blank=True, db_column='carreraAlumno', max_length=100, null=True)),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('iddesafio', models.AutoField(db_column='idDesafio', primary_key=True, serialize=False)),
                ('nombredesafio', models.CharField(blank=True, db_column='nombreDesafio', max_length=100, null=True)),
                ('tokensdesafio', models.IntegerField(blank=True, db_column='tokensDesafio', null=True)),
            ],
            options={
                'db_table': 'desafio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Desafiolego',
            fields=[
                ('iddesafiolego', models.AutoField(db_column='idDesafioLego', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'desafiolego',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('action_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('idencuesta', models.AutoField(db_column='idEncuesta', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'encuesta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('idevaluacion', models.AutoField(db_column='idEvaluacion', primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('grupoevaluado', models.IntegerField(blank=True, db_column='grupoEvaluado', null=True)),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('idgrupo', models.AutoField(db_column='idGrupo', primary_key=True, serialize=False)),
                ('tokensGrupo', models.IntegerField(blank=True, null=True)),
                ('etapa', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Idadministrador',
            fields=[
                ('idadministrador', models.AutoField(db_column='idAdministrador', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'idadministrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapaempatia',
            fields=[
                ('idmapaempatia', models.AutoField(db_column='idMapaEmpatia', primary_key=True, serialize=False)),
                ('emociones', models.CharField(blank=True, max_length=200, null=True)),
                ('gustos', models.CharField(blank=True, max_length=200, null=True)),
                ('entorno', models.CharField(blank=True, max_length=200, null=True)),
                ('necesidades', models.CharField(blank=True, max_length=200, null=True)),
                ('limitaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('motivaciones', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'mapaempatia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('idprofesor', models.AutoField(db_column='idProfesor', primary_key=True, serialize=False)),
                ('emailprofesor', models.CharField(blank=True, max_length=100, null=True)),
                ('facultad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'profesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('idreto', models.AutoField(db_column='idReto', primary_key=True, serialize=False)),
                ('nombrereto', models.CharField(blank=True, db_column='nombreReto', max_length=90, null=True)),
                ('descripcionreto', models.CharField(blank=True, db_column='descripcionReto', max_length=200, null=True)),
                ('recompensareto', models.CharField(blank=True, db_column='recompensaReto', max_length=100, null=True)),
                ('costoreto', models.CharField(blank=True, db_column='costoReto', max_length=90, null=True)),
            ],
            options={
                'db_table': 'reto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('idtokens', models.AutoField(db_column='idTokens', primary_key=True, serialize=False)),
                ('numtokens', models.IntegerField(blank=True, db_column='numTokens', null=True)),
            ],
            options={
                'db_table': 'tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
