# Generated by Django 5.2.7 on 2025-11-12 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desafiolego',
            fields=[
                ('iddesafiolego', models.AutoField(db_column='idDesafioLego', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'desafiolego',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('idgrupo', models.AutoField(db_column='idGrupo', primary_key=True, serialize=False)),
                ('tokensgrupo', models.IntegerField(blank=True, default=12, null=True)),
                ('etapa', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Idadministrador',
            fields=[
                ('idadministrador', models.AutoField(db_column='idAdministrador', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'idadministrador',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('idprofesor', models.AutoField(db_column='idProfesor', primary_key=True, serialize=False)),
                ('emailprofesor', models.CharField(blank=True, max_length=100, null=True)),
                ('facultad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'profesor',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('idevaluacion', models.AutoField(db_column='idEvaluacion', primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('grupoevaluado', models.IntegerField(blank=True, db_column='grupoEvaluado', null=True)),
                ('desafiolego_iddesafiolego', models.ForeignKey(db_column='desafioLego_idDesafioLego', on_delete=django.db.models.deletion.DO_NOTHING, to='juego.desafiolego')),
            ],
            options={
                'db_table': 'evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('idencuesta', models.AutoField(db_column='idEncuesta', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('grupo_idgrupo', models.ForeignKey(db_column='grupo_idGrupo', on_delete=django.db.models.deletion.DO_NOTHING, to='juego.grupo')),
            ],
            options={
                'db_table': 'encuesta',
            },
        ),
        migrations.AddField(
            model_name='desafiolego',
            name='grupo_idgrupo',
            field=models.ForeignKey(db_column='grupo_idGrupo', on_delete=django.db.models.deletion.DO_NOTHING, to='juego.grupo'),
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('iddesafio', models.AutoField(db_column='idDesafio', primary_key=True, serialize=False)),
                ('nombredesafio', models.CharField(blank=True, db_column='nombreDesafio', max_length=100, null=True)),
                ('tokensdesafio', models.IntegerField(blank=True, db_column='tokensDesafio', null=True)),
                ('descripciondesafio', models.CharField(blank=True, db_column='descripcionDesafio', max_length=300, null=True)),
                ('idadministrador_idadministrador', models.ForeignKey(db_column='idadministrador_idAdministrador', on_delete=django.db.models.deletion.DO_NOTHING, to='juego.idadministrador')),
            ],
            options={
                'db_table': 'desafio',
            },
        ),
        migrations.CreateModel(
            name='Mapaempatia',
            fields=[
                ('idmapaempatia', models.AutoField(db_column='idMapaEmpatia', primary_key=True, serialize=False)),
                ('emociones', models.CharField(blank=True, max_length=200, null=True)),
                ('gustos', models.CharField(blank=True, max_length=200, null=True)),
                ('entorno', models.CharField(blank=True, max_length=200, null=True)),
                ('necesidades', models.CharField(blank=True, max_length=200, null=True)),
                ('limitaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('motivaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('desafio_iddesafio', models.ForeignKey(db_column='desafio_idDesafio', on_delete=django.db.models.deletion.DO_NOTHING, to='juego.desafio')),
            ],
            options={
                'db_table': 'mapaempatia',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idalumno', models.AutoField(db_column='idAlumno', primary_key=True, serialize=False)),
                ('emailalumno', models.CharField(blank=True, db_column='emailAlumno', max_length=100, null=True)),
                ('rutalumno', models.CharField(blank=True, db_column='rutAlumno', max_length=100, null=True)),
                ('nombrealumno', models.CharField(blank=True, db_column='nombreAlumno', max_length=200, null=True)),
                ('apellidopaternoalumno', models.CharField(blank=True, db_column='apellidoPaternoAlumno', max_length=100, null=True)),
                ('apellidomaternoalumno', models.CharField(blank=True, db_column='apellidoMaternoAlumno', max_length=100, null=True)),
                ('carreraalumno', models.CharField(blank=True, db_column='carreraAlumno', max_length=100, null=True)),
                ('profesor_idprofesor', models.ForeignKey(db_column='profesor_idProfesor', on_delete=django.db.models.deletion.DO_NOTHING, to='juego.profesor')),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('idreto', models.AutoField(db_column='idReto', primary_key=True, serialize=False)),
                ('nombrereto', models.CharField(blank=True, db_column='nombreReto', max_length=90, null=True)),
                ('descripcionreto', models.CharField(blank=True, db_column='descripcionReto', max_length=200, null=True)),
                ('recompensareto', models.CharField(blank=True, db_column='recompensaReto', max_length=100, null=True)),
                ('costoreto', models.IntegerField(blank=True, db_column='costoReto', null=True)),
                ('desafio_iddesafio', models.ForeignKey(db_column='desafio_idDesafio', on_delete=django.db.models.deletion.DO_NOTHING, to='juego.desafio')),
            ],
            options={
                'db_table': 'reto',
            },
        ),
        migrations.AddField(
            model_name='desafiolego',
            name='reto_idreto',
            field=models.ForeignKey(db_column='reto_idReto', on_delete=django.db.models.deletion.DO_NOTHING, to='juego.reto'),
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('idtokens', models.AutoField(db_column='idTokens', primary_key=True, serialize=False)),
                ('numtokens', models.IntegerField(blank=True, db_column='numTokens', null=True)),
                ('grupo_idgrupo', models.ForeignKey(db_column='grupo_idGrupo', on_delete=django.db.models.deletion.DO_NOTHING, to='juego.grupo')),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario_idusuario',
            field=models.ForeignKey(db_column='usuario_idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='juego.usuario'),
        ),
        migrations.AddField(
            model_name='idadministrador',
            name='usuario_idusuario',
            field=models.ForeignKey(db_column='usuario_idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='juego.usuario'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='usuario_idusuario',
            field=models.ForeignKey(db_column='usuario_idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='juego.usuario'),
        ),
    ]
