# Generated by Django 5.0.6 on 2025-11-18 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(blank=True, db_column='grupo_idGrupo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='juego.grupo'),
        ),
    ]
