# Generated by Django 5.0.6 on 2025-11-18 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_alumno_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='usuario_idusuario',
            field=models.ForeignKey(blank=True, db_column='usuario_idUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='juego.usuario'),
        ),
    ]
