# Generated by Django 5.2.7 on 2025-11-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_alter_grupo_usuario_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='codigoacceso',
            field=models.CharField(blank=True, db_column='codigoAcceso', max_length=8, null=True, unique=True),
        ),
    ]
