# Generated by Django 5.2.7 on 2025-12-01 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0004_grupo_codigoacceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='nombregrupo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='etapa',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('idsesion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(db_column='profesor_idProfesor', on_delete=django.db.models.deletion.CASCADE, to='juego.profesor')),
            ],
            options={
                'db_table': 'sesion',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='sesion',
            field=models.ForeignKey(db_column='sesion_idSesion', null=True, on_delete=django.db.models.deletion.CASCADE, to='juego.sesion'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='sesion',
            field=models.ForeignKey(db_column='sesion_idSesion', null=True, on_delete=django.db.models.deletion.CASCADE, to='juego.sesion'),
        ),
    ]
