# Generated by Django 5.2.7 on 2025-12-02 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0005_grupo_nombregrupo_alter_grupo_etapa_sesion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reto',
            name='desafio_iddesafio',
            field=models.ForeignKey(blank=True, db_column='desafio_idDesafio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='juego.desafio'),
        ),
        migrations.CreateModel(
            name='Retogrupo',
            fields=[
                ('idretogrupo', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('COMP', 'Completado'), ('FALL', 'Fallado')], default='PEND', max_length=4)),
                ('tokens_costo', models.IntegerField(default=0)),
                ('tokens_recompensa', models.IntegerField(default=0)),
                ('tokens_penalizacion', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('grupo_emisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='retos_enviados', to='juego.grupo')),
                ('grupo_receptor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='retos_recibidos', to='juego.grupo')),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='juego.reto')),
            ],
            options={
                'db_table': 'retogrupo',
            },
        ),
    ]
