# Generated by Django 5.2.7 on 2025-12-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0006_alter_reto_desafio_iddesafio_retogrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='sopa_ganada',
            field=models.BooleanField(default=False),
        ),
    ]
