# Generated by Django 5.2.7 on 2025-12-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0007_grupo_sopa_ganada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='tokensgrupo',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
