# Generated by Django 5.2.7 on 2025-12-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0008_alter_grupo_tokensgrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='orden_presentacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
