# Generated by Django 5.2.7 on 2025-12-02 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0009_grupo_orden_presentacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evaluacion',
        ),
    ]
