# Generated by Django 5.2.7 on 2025-12-02 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0010_delete_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('idevaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('claridad', models.IntegerField()),
                ('creatividad', models.IntegerField()),
                ('viabilidad', models.IntegerField()),
                ('equipo', models.IntegerField()),
                ('presentacion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('reflexion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('grupo_evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_recibidas', to='juego.grupo')),
                ('grupo_evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_enviadas', to='juego.grupo')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='juego.sesion')),
            ],
            options={
                'db_table': 'evaluacion',
                'unique_together': {('sesion', 'grupo_evaluador', 'grupo_evaluado')},
            },
        ),
    ]
