# Generated by Django 5.2.7 on 2025-12-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0011_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='recompensa_peer_otorgada',
            field=models.BooleanField(default=False),
        ),
    ]
