# Generated by Django 5.2.7 on 2026-03-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0012_grupo_recompensa_peer_otorgada"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="listo_f1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="grupo",
            name="listo_f2",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="grupo",
            name="listo_f3",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="grupo",
            name="listo_f4",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="grupo",
            name="listo_lobby",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sesion",
            name="fase_actual",
            field=models.CharField(default="lobby", max_length=40),
        ),
        migrations.AddField(
            model_name="sesion",
            name="segundos_restantes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sesion",
            name="t_creatividad",
            field=models.IntegerField(default=900),
        ),
        migrations.AddField(
            model_name="sesion",
            name="t_diferencias",
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name="sesion",
            name="t_empatia",
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name="sesion",
            name="t_pitch",
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name="sesion",
            name="t_pitch_prep",
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name="sesion",
            name="t_rompehielo",
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name="sesion",
            name="timer_corriendo",
            field=models.BooleanField(default=False),
        ),
    ]
