# Generated by Django 5.2.7 on 2026-03-27 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0013_grupo_listo_f1_grupo_listo_f2_grupo_listo_f3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="desafio_elegido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grupos_que_lo_eligieron",
                to="juego.desafio",
            ),
        ),
        migrations.AddField(
            model_name="grupo",
            name="listo_f2_desafio",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="grupo",
            name="listo_f2_tematica",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="grupo",
            name="tema_elegido",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
