# Generated by Django 5.2.7 on 2026-03-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0014_grupo_desafio_elegido_grupo_listo_f2_desafio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="listo_f5",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="grupo",
            name="listo_f6",
            field=models.BooleanField(default=False),
        ),
    ]
