# Generated by Django 5.2.7 on 2026-03-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0015_grupo_listo_f5_grupo_listo_f6"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="foto_lego",
            field=models.ImageField(blank=True, null=True, upload_to="legos/"),
        ),
        migrations.AddField(
            model_name="grupo",
            name="pitch_texto",
            field=models.TextField(blank=True, null=True),
        ),
    ]
