# Generated by Django 5.2.7 on 2026-03-28 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0016_grupo_foto_lego_grupo_pitch_texto"),
    ]

    operations = [
        migrations.AddField(
            model_name="sesion",
            name="grupo_presentando",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sesiones_como_presentador_actual",
                to="juego.grupo",
            ),
        ),
    ]
