# Generated by Django 5.2.7 on 2026-03-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0017_sesion_grupo_presentando"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="listo_ranking",
            field=models.BooleanField(default=False),
        ),
    ]
