# Generated by Django 5.2.7 on 2026-03-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0018_grupo_listo_ranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sesion",
            name="fase_actual",
            field=models.CharField(default="f1_bienvenida", max_length=40),
        ),
    ]
