# Generated by Django 5.2.7 on 2026-03-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0019_alter_sesion_fase_actual"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="desafio_descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grupo",
            name="desafio_id_externo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="grupo",
            name="desafio_nombre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
