# Generated by Django 5.2.7 on 2026-04-01 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0020_grupo_desafio_descripcion_grupo_desafio_id_externo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sesion",
            name="timer_fin_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sesion",
            name="timer_inicio_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PalabraSopaEncontrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("palabra", models.CharField(max_length=80)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="palabras_sopa",
                        to="juego.grupo",
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="palabras_sopa",
                        to="juego.sesion",
                    ),
                ),
            ],
            options={
                "db_table": "palabra_sopa_encontrada",
                "unique_together": {("sesion", "grupo", "palabra")},
            },
        ),
    ]
