# Generated by Django 5.2.7 on 2026-04-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0021_sesion_timer_fin_at_sesion_timer_inicio_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="listo_f2_empatia",
            field=models.BooleanField(default=False),
        ),
    ]
