# Generated by Django 5.2.7 on 2026-04-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0022_grupo_listo_f2_empatia"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="lego_sin_foto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="grupo",
            name="listo_f3_lego",
            field=models.BooleanField(default=False),
        ),
    ]
