# Generated by Django 5.2.7 on 2026-04-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0023_grupo_lego_sin_foto_grupo_listo_f3_lego"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="listo_inicio_f3",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sesion",
            name="inicio_fase_habilitado",
            field=models.BooleanField(default=False),
        ),
    ]
