# Generated by Django 5.2.7 on 2026-04-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0024_grupo_listo_inicio_f3_sesion_inicio_fase_habilitado"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="bubble_tokens_otorgados",
            field=models.BooleanField(default=False),
        ),
    ]
