# Generated by Django 5.2.7 on 2026-04-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0025_grupo_bubble_tokens_otorgados"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="listo_f4_orden",
            field=models.BooleanField(default=False),
        ),
    ]
