# Generated by Django 5.2.7 on 2026-04-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0026_grupo_listo_f4_orden"),
    ]

    operations = [
        migrations.AddField(
            model_name="sesion",
            name="orden_sorteado",
            field=models.BooleanField(default=False),
        ),
    ]
