# Generated by Django 5.2.7 on 2026-04-29 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0027_sesion_orden_sorteado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('idtematica', models.AutoField(db_column='idTematica', primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('hero', models.TextField(blank=True, null=True)),
                ('chips', models.JSONField(blank=True, default=list)),
                ('accent', models.CharField(default='#3b82f6', max_length=20)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'tematica',
                'ordering': ['orden', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='desafio',
            options={'ordering': ['orden', 'nombredesafio']},
        ),
        migrations.AddField(
            model_name='desafio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desafio',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='descripciondesafio',
            field=models.TextField(blank=True, db_column='descripcionDesafio', null=True),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='idadministrador_idadministrador',
            field=models.ForeignKey(blank=True, db_column='idadministrador_idAdministrador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='juego.idadministrador'),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='nombredesafio',
            field=models.CharField(blank=True, db_column='nombreDesafio', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='tematica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desafios', to='juego.tematica'),
        ),
    ]
