# Generated by Django 5.2.7 on 2026-04-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0028_tematica_alter_desafio_options_desafio_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='imagen_desafio',
            field=models.ImageField(blank=True, null=True, upload_to='desafios/'),
        ),
    ]
