# Generated by Django 5.2.7 on 2026-04-30 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0029_desafio_imagen_desafio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BubbleMapRespuesta',
            fields=[
                ('idrespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('relato', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('desafio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bubble_respuestas', to='juego.desafio')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubble_respuestas', to='juego.grupo')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubble_respuestas', to='juego.sesion')),
            ],
            options={
                'db_table': 'bubblemap_respuesta',
            },
        ),
    ]
