# Generated by Django 5.2.7 on 2026-04-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0030_bubblemaprespuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuletaLegoOpcion',
            fields=[
                ('idopcion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.SlugField(max_length=80, unique=True)),
                ('emoji', models.CharField(blank=True, max_length=20, null=True)),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tokens', models.IntegerField(default=0)),
                ('porcentaje', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'ruleta_lego_opcion',
                'ordering': ['orden', 'titulo'],
            },
        ),
    ]
