# Generated by Django 5.2.7 on 2026-04-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0031_ruletalegoopcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiempoFase',
            fields=[
                ('idtiempo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('segundos', models.PositiveIntegerField(default=60)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'tiempo_fase',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
