# Generated by Django 5.2.7 on 2026-04-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0032_tiempofase'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='t_presentacion',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='sesion',
            name='t_tematicas',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
