# Generated by Django 5.2.7 on 2026-05-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0033_sesion_t_presentacion_sesion_t_tematicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='t_creatividad',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='t_pitch_prep',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='t_rompehielo',
            field=models.IntegerField(default=120),
        ),
    ]
