# Generated by Django 5.2.7 on 2026-05-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0034_alter_sesion_t_creatividad_alter_sesion_t_pitch_prep_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="sopa_completada_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grupo",
            name="sopa_tiempo_segundos",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
