# Generated by Django 5.2.7 on 2026-05-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0035_grupo_sopa_completada_en_grupo_sopa_tiempo_segundos"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="listo_f2_tematicas",
            field=models.BooleanField(default=False),
        ),
    ]
